language: java
env:
  - SPRING_PROFILES_ACTIVE=development
jdk:
  - oraclejdk8
before_script:
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >t.jar
  - java -jar t.jar -u init
  - rm t.jar
  - /home/travis/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
script: gradle test jacocoTestReport --info
after_script:
  - /home/travis/jpm/bin/codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
