# You can use multiple profiles to easily configure for test and production.
# Copy this file to `<project root>/src/main/resources/application.yaml`.
---
spring:
  profiles: cloud
# #
# # Set a secure password for your broker client.
# #
# security:
#   user:
#     password: somethingsecure
# #
# # Set the required configuration fields for a true ECS cluster.
# #
# broker:
#   namespace:
#   replication-group:
#   management-endpoint:
#   base-url:
catalog:
  services:
    - id: 09cac1c6-1b0a-11e6-b6ba-3e1d05defe78
      name: ecs-namespace
      description: Elastic Cloud Namespace
      bindable: true
      plan-updatable: true
      tags:
        - s3
        - namespace
      service-settings:
        service-type: namespace
      metadata:
        displayName: ecs-namespace
        imageUrl: http://www.emc.com/images/products/header-image-icon-ecs.png
        longDescription: Dell EMC Elastic Cloud Storage (ECS) Namespace for managing Amazon S3, Swift or Atmos buckets.
        providerDisplayName: Dell EMC
        documentationUrl: https://community.emc.com/docs/DOC-45012
        supportUrl: http://www.emc.com/products-solutions/trial-software-download/ecs.htm
      plans:
        - id: 09cac5b8-1b0a-11e6-b6ba-3e1d05defe78
          name: 5gb
          description: Free Trial
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 5.0
                unit: MONTHLY
            bullets:
              - Multiple Bucket Namespace
              - 5 GB Storage
              - S3 protocol and HDFS access
    - id: f3cbab6a-5172-4ff1-a5c7-72990f0ce2aa
      name: ecs-bucket
      type: bucket
      description: Elastic Cloud S3 Object Storage Bucket
      bindable: true
      plan-updatable: true
      tags:
        - s3
        - bucket
      service-settings:
        service-type: bucket
        head-type: s3
        access-during-outage: true
      metadata:
        displayName: ecs-bucket
        imageUrl: http://www.emc.com/images/products/header-image-icon-ecs.png
        longDescription: Dell EMC Elastic Cloud Storage (ECS) Object bucket for storing data using Amazon S3.
        providerDisplayName: Dell EMC
        documentationUrl: https://community.emc.com/docs/DOC-45012
        supportUrl: http://www.emc.com/products-solutions/trial-software-download/ecs.htm
      plans:
        - id: 8e777d49-0a78-4cf4-810a-b5f5173b019d
          name: 5gb
          description: Free Trial
          service-settings:
            quota:
              limit: 5
              warn: 4
          free: true
          metadata:
            costs:
              - amount:
                  usd: 0.0
                unit: MONTHLY
            bullets:
              - Shared object storage
              - 5 GB Storage
              - S3 protocol access
        - id: 89d20694-9ab0-4a98-bc6a-868d6d4ecf31
          name: unlimited
          description: Pay per GB for Month
          metadata:
            costs:
              - amount:
                  usd: 0.03
                unit: PER GB PER MONTH
            bullets:
              - Shared object storage
              - Unlimited Storage
              - S3 protocol access
    - id: 9052313c-20b2-47de-900f-6e8b04fafcca
      name: ecs-file-bucket
      type: bucket
      description: Elastic Cloud S3 Object Storage File Accessible Bucket
      bindable: true
      plan-updatable: true
      tags:
        - s3
        - bucket
        - nfs
        - hdfs
      requires:
        - volume_mount
      service-settings:
        service-type: bucket
        head-type: s3
        access-during-outage: true
        file-accessible: true
      metadata:
        displayName: ecs-file-bucket
        imageUrl: http://www.emc.com/images/products/header-image-icon-ecs.png
        longDescription: Dell EMC Elastic Cloud Storage (ECS) Object bucket for storing data using Amazon S3 or NFS.
        providerDisplayName: Dell EMC
        documentationUrl: https://community.emc.com/docs/DOC-45012
        supportUrl: http://www.emc.com/products-solutions/trial-software-download/ecs.htm
      plans:
        - id: b7c3f0b0-6867-44e3-b1b9-b255852010b3
          name: 5gb
          description: Free Trial
          service-settings:
            quota:
              limit: 5
              warn: 4
          free: true
          metadata:
            costs:
              - amount:
                  usd: 0.0
                unit: MONTHLY
            bullets:
              - Shared object storage
              - 5 GB Storage
              - S3 protocol and HDFS access
        - id: 285817bc-e73d-4bb4-bd5d-aebe54ef792f
          name: unlimited
          description: Pay per GB for Month
          metadata:
            costs:
              - amount:
                  usd: 0.03
                unit: PER GB PER MONTH
            bullets:
              - Shared object storage
              - Unlimited Storage
              - S3 protocol and HDFS access
