apiVersion: v1
kind: ConfigMap
metadata:
  name: ecs-broker
data:
  application.yml: |-
    ---
    broker:
      object-endpoint: {{ .Values.api.endpoint }}
      management-endpoint: {{ .Values.ecsConnection.endpoint }}
      namespace: {{ .Values.namespace }}
      replication-group: {{ .Values.replicationGroup }}
      prefix: {{ .Values.prefix }}
  {{- if .Values.certificate }}
      certificate: {{ toYaml .Values.certificate | indent 6 }}
  {{- end }}
      defaultReclaimPolicy: {{ .Values.defaultReclaimPolicy }}
    {{- template "ecs-service-broker.catalog" . }}
    spring:
      profiles: default
